[project]
name = "leetcode"
version = "0.0.1"
description = "Leetcode solutions"
authors = [
    {name = "Iurii Alekseev", email = "iurii.alekseev.inbox@gmail.com"},
]
dependencies = [
    "ruff",
    "sqlfluff",
]
requires-python = ">=3.12"
